import {
  DEFAULT_AI_DIR,
  DEFAULT_CARDS_DIR,
  DEFAULT_ROOT_DIR,
  DEFAULT_SOURCES_DIR,
  DEFAULT_SUGGESTIONS_DIR,
  DEFAULT_READING_REVIEWS_DIR,
  DEFAULT_DAILY_DIR,
} from "./constants";
import type { ReadMindPluginData, ReadMindSettings } from "./types";

export const DEFAULT_SETTINGS: ReadMindSettings = {
  schemaVersion: 1,
  dataSourceMode: "fixture",
  rootDir: DEFAULT_ROOT_DIR,
  sourcesDir: DEFAULT_SOURCES_DIR,
  aiDir: DEFAULT_AI_DIR,
  cardsDir: DEFAULT_CARDS_DIR,
  suggestionsDir: DEFAULT_SUGGESTIONS_DIR,
  readingReviewsDir: DEFAULT_READING_REVIEWS_DIR,
  importedData: undefined,
  wereadConnection: {
    state: "disconnected",
    message: "尚未连接微信读书。",
  },
  wereadSession: undefined,
  wereadOfficial: {
    apiKey: "",
    skillVersion: "1.0.3",
    connection: {
      state: "disconnected",
      message: "尚未连接微信读书官方 API。",
    },
  },
  weReadDebugEnabled: false,
  dailyNotes: {
    enabled: false,
    folder: DEFAULT_DAILY_DIR,
    dateFormat: "YYYY-MM-DD",
    includeSyncedAnnotations: true,
    includeAIAnalysis: true,
    includeCards: true,
    includeAcceptedLinks: true,
  },
  templates: {
    sourceNote: "default-source-v1",
    aiAnalysis: "default-analysis-v1",
    knowledgeCard: "default-card-v1",
    dailyNote: "default-daily-v1",
  },
  frontmatter: {
    enabled: true,
    includeBookId: true,
    includeSource: true,
    includeTitle: true,
    includeAuthor: true,
    includeSyncStatus: true,
    includeAIStatus: true,
    includeTags: true,
  },
  prompts: {
    version: "prompt-v1",
    bookAnalysis: "",
    knowledgeCard: "",
    linkSuggestion: "",
  },
  ai: {
    enabled: false,
    providerType: "openai-compatible",
    providerId: "qwen",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    apiKey: "",
    model: "qwen3.6-max-preview",
    customModel: "qwen3.6-max-preview",
    temperature: 0.2,
    maxInputChars: 12000,
    includeUserThoughts: true,
    includeMetadata: true,
  },
  firstAnalysisConfirmed: false,
};

export const DEFAULT_PLUGIN_DATA: ReadMindPluginData = {
  settings: DEFAULT_SETTINGS,
  syncIndex: {},
  analysisIndex: {},
  cardIndex: {},
  linkSuggestions: {},
  relationSuggestions: {},
  confirmedRelations: {},
  readingReviewIndex: {},
  knowledgeNetworkLayout: {
    nodePositions: {},
    viewport: { x: 0, y: 0, scale: 1 },
    updatedAt: "",
  },
  dailyEvents: [],
  selectedBookIds: [],
  syncLogs: [],
};
