import { stableJsonHash } from "./hash";
import type { ImportedReadingData, ReadingAnnotation, ReadingBookDetails } from "./types";

function annotation(input: Omit<ReadingAnnotation, "sourceHash">): ReadingAnnotation {
  return {
    ...input,
    sourceHash: stableJsonHash(input),
  };
}

const books: ReadingBookDetails[] = [
  {
    id: "fixture-clear-thinking",
    source: "fixture",
    title: "清醒思考的练习",
    author: "ReadMind Demo",
    publisher: "本地示例",
    category: "思维方法",
    description: "一本虚构的演示书，用来展示划线、想法和同步流程。",
    readingStatus: "reading",
    annotationCount: 4,
    thoughtCount: 2,
    lastReadAt: "2026-05-21T09:30:00+08:00",
    sourceUpdatedAt: "2026-05-21T09:30:00+08:00",
    annotations: [
      annotation({
        id: "ct-001",
        bookId: "fixture-clear-thinking",
        chapterId: "c1",
        chapterTitle: "第一章：慢一点判断",
        type: "highlight",
        text: "一个判断在说出口之前，最好先经过事实、解释和行动三个层面的拆分。",
        locationLabel: "第 1 章 位置 12",
        createdAt: "2026-05-20T20:00:00+08:00",
      }),
      annotation({
        id: "ct-002",
        bookId: "fixture-clear-thinking",
        chapterId: "c1",
        chapterTitle: "第一章：慢一点判断",
        type: "thought",
        text: "这很适合放进日常复盘：我看见了什么，我推断了什么，我准备做什么。",
        relatedHighlightId: "ct-001",
        locationLabel: "第 1 章 位置 13",
        createdAt: "2026-05-20T20:02:00+08:00",
      }),
      annotation({
        id: "ct-003",
        bookId: "fixture-clear-thinking",
        chapterId: "c2",
        chapterTitle: "第二章：保留反证",
        type: "highlight",
        text: "真正稳固的观点，不怕被反例靠近；它需要知道自己在哪里可能失效。",
        locationLabel: "第 2 章 位置 8",
        createdAt: "2026-05-21T09:20:00+08:00",
      }),
      annotation({
        id: "ct-004",
        bookId: "fixture-clear-thinking",
        chapterId: "c2",
        chapterTitle: "第二章：保留反证",
        type: "thought",
        text: "以后整理观点时，可以专门留一栏写“我可能错在哪里”。",
        relatedHighlightId: "ct-003",
        locationLabel: "第 2 章 位置 9",
        createdAt: "2026-05-21T09:30:00+08:00",
      }),
    ],
  },
  {
    id: "fixture-deep-reading",
    source: "fixture",
    title: "深度阅读的路径",
    author: "ReadMind Demo",
    publisher: "本地示例",
    category: "阅读方法",
    description: "一本虚构的演示书，用来展示跨书阅读材料。",
    readingStatus: "finished",
    annotationCount: 4,
    thoughtCount: 1,
    lastReadAt: "2026-05-22T11:00:00+08:00",
    sourceUpdatedAt: "2026-05-22T11:00:00+08:00",
    annotations: [
      annotation({
        id: "dr-001",
        bookId: "fixture-deep-reading",
        chapterId: "d1",
        chapterTitle: "第一章：带着问题进入文本",
        type: "highlight",
        text: "阅读不是收集句子，而是让问题和材料彼此校正。",
        locationLabel: "第 1 章 位置 4",
        createdAt: "2026-05-22T10:00:00+08:00",
      }),
      annotation({
        id: "dr-002",
        bookId: "fixture-deep-reading",
        chapterId: "d1",
        chapterTitle: "第一章：带着问题进入文本",
        type: "thought",
        text: "可以把每本书的核心问题写进来源笔记顶部。",
        relatedHighlightId: "dr-001",
        locationLabel: "第 1 章 位置 5",
        createdAt: "2026-05-22T10:05:00+08:00",
      }),
      annotation({
        id: "dr-003",
        bookId: "fixture-deep-reading",
        chapterId: "d2",
        chapterTitle: "第二章：把摘录还给语境",
        type: "highlight",
        text: "脱离语境的摘录容易变成漂亮但含混的标本，回链能帮助它重新接上上下文。",
        locationLabel: "第 2 章 位置 18",
        createdAt: "2026-05-22T10:40:00+08:00",
      }),
      annotation({
        id: "dr-004",
        bookId: "fixture-deep-reading",
        chapterId: "d2",
        chapterTitle: "第二章：把摘录还给语境",
        type: "highlight",
        text: "一张好的知识卡片，应该能说明它从哪里来，也能留下继续生长的空间。",
        locationLabel: "第 2 章 位置 21",
        createdAt: "2026-05-22T11:00:00+08:00",
      }),
    ],
  },
];

export const fixtureData: ImportedReadingData = { books };
